### ISSUE TITLE
`col_select` doesn't work with selection helpers

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phslookups#8]
`col_select` should work with selection helpers, e.g. it should be possible to do `get_spd(col_select = c("pc7", dplyr::starts_with("hscp"))` but this doesn't work. I guess it's something to do with how it's being passed between functions and tied up with 'non-standard evaluation' etc. which just hurts my head!

**Comment by Nic-Chr** [comment]
Try replacing `!!col_select` with `{{ col_select }}`. I think the former can theoretically also only work with 1 column.

**Comment by Nic-Chr** [comment]
I've hopefully fixed the issue in the new PR #9
